name: Build CI

on: [push]

jobs:
  build:

    runs-on: [windows-latest]
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        architecture: x86 
    - run: yarn
    - run: yarn build
    - run: yarn test
      env:
        CI: true
    
    


